export enum Role {
  ADMIN = 'ADMIN',
  ORGANIZER = 'ORGANIZER',
  HORSE_OWNER = 'HORSE_OWNER',
  SPECTATOR = 'SPECTATOR',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  LOCKED = 'LOCKED',
}

export enum HorseStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISQUALIFIED = 'DISQUALIFIED',
}

export enum JockeyStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum SeasonStatus {
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  CLOSED = 'CLOSED',
}

export enum RaceStatus {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum RegistrationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DopingResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
}

export enum NotificationType {
  REGISTRATION = 'REGISTRATION',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
  RESULT = 'RESULT',
  SYSTEM = 'SYSTEM',
}

export enum FileType {
  HORSE_PHOTO = 'HORSE_PHOTO',
  PASSPORT_SCAN = 'PASSPORT_SCAN',
  HEALTH_CERTIFICATE = 'HEALTH_CERTIFICATE',
  JOCKEY_AVATAR = 'JOCKEY_AVATAR',
  LICENSE_SCAN = 'LICENSE_SCAN',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  DOPING_REPORT = 'DOPING_REPORT',
  HEALTH_RECORD_ATTACHMENT = 'HEALTH_RECORD_ATTACHMENT',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE_HORSE = 'APPROVE_HORSE',
  REJECT_HORSE = 'REJECT_HORSE',
  DISQUALIFY_HORSE = 'DISQUALIFY_HORSE',
  APPROVE_JOCKEY = 'APPROVE_JOCKEY',
  REJECT_JOCKEY = 'REJECT_JOCKEY',
  APPROVE_REGISTRATION = 'APPROVE_REGISTRATION',
  REJECT_REGISTRATION = 'REJECT_REGISTRATION',
  PUBLISH_RESULT = 'PUBLISH_RESULT',
  UPLOAD_FILE = 'UPLOAD_FILE',
  LOCK_USER = 'LOCK_USER',
  CHANGE_ROLE = 'CHANGE_ROLE',
}